{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.applicationName -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressClass := .Values.ingress.class |default .Values.ingressClass -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress-{{ .Values.environment }}
  labels:
  {{- include "telus.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ $ingressClass | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    {{- include "telus.annotations" . | nindent 4}}
    {{- if .Values.ingress.kongPlugins }}
    plugins.konghq.com: {{ .Values.ingress.kongPlugins }}
    {{- end }}
    {{- if .Values.ingress.annotations }}{{- range $name, $value := .Values.ingress.annotations }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value | quote }}
    {{- end }}{{- end }}{{- end }}
  namespace: {{ .Values.namespace }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ default "UNKNOWN-HOST" .  | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-{{ $.Values.environment }}
              servicePort: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
          
