{{- if .Values.kong.enabled }}
{{- range .Values.kong.credentials }}
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: {{ .name }}
  labels:
    {{- include "telus.labels" $ | nindent 4 }}
  annotations:
    {{- include "telus.annotations" $ | nindent 4}} 
consumerRef: {{ .consumer }}
type: {{ .type }}
config:
{{- if eq .type "key-auth"}}
  key: "{{ randAlphaNum 32 }}"
{{- end }}
{{- with .config }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}