{{- if .Values.openshift.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.applicationName }}-{{ .Values.environment }}
    {{- include "telus.labels" . | nindent 4 }}
  annotations:
    {{- include "telus.annotations" . | nindent 4}}    
  namespace: {{ .Values.namespace }}
spec:
  path: {{ .Values.openshift.path }}
  host: {{ .Values.openshift.host }}
  to:
    kind: Service
    name: {{ .Values.applicationName }}-{{ .Values.environment }}
    weight: 100
  wildcardPolicy: None
{{- end }}